// WP-7.4 (D-56, D-53; issue #153). Converts the reviewed pilot photos in
// docs/catalog-source/ (not tracked — supplier originals) into
// public/catalog/<key>.webp, and regenerates the shipped-file manifest
// the server validates `imageFile` against and the admin select offers.
//
//   pnpm catalog:images
//
// One format and one bounded size: trimmed of the supplier's own margin,
// flattened on white, then fitted into a square so the S-01 grid lines
// up. Re-run after changing the CSV or a source photo; output is
// deterministic for the same input.
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import sharp from 'sharp'
import { readPilotCatalog } from './lib/pilot-catalog-csv'

const SOURCE_DIR = 'docs/catalog-source'
const OUTPUT_DIR = 'public/catalog'
const MANIFEST = 'server/utils/catalog-image-manifest.ts'
const SIZE = 800
const WHITE = { r: 255, g: 255, b: 255, alpha: 1 }

// macOS writes decomposed diacritics into file names (NFD); the CSV holds
// composed ones (NFC). Match on the normalised form, open the real name.
function sourceFiles(): Map<string, string> {
  return new Map(readdirSync(SOURCE_DIR).map((name) => [name.normalize('NFC'), name]))
}

async function main() {
  const rows = readPilotCatalog(join(SOURCE_DIR, 'pilot-catalog.csv'))
  const sources = sourceFiles()

  rmSync(OUTPUT_DIR, { recursive: true, force: true })
  mkdirSync(OUTPUT_DIR, { recursive: true })

  const shipped: string[] = []
  const missing: string[] = []
  for (const row of rows) {
    if (!row.sourceImage) {
      missing.push(row.key)
      continue
    }
    const source = sources.get(row.sourceImage.normalize('NFC'))
    if (!source || !existsSync(join(SOURCE_DIR, source))) {
      throw new Error(`${row.key}: source photo "${row.sourceImage}" is not in ${SOURCE_DIR}.`)
    }

    const output = `${row.key}.webp`
    // Two passes because sharp does not apply operations in call order:
    // trim against the corner pixel first (a transparent or a white
    // margin alike), then flatten and fit.
    const trimmed = await sharp(join(SOURCE_DIR, source)).trim({ threshold: 12 }).png().toBuffer()
    await sharp(trimmed)
      .flatten({ background: WHITE })
      .resize(SIZE, SIZE, { fit: 'contain', background: WHITE })
      .webp({ quality: 80 })
      .toFile(join(OUTPUT_DIR, output))
    shipped.push(output)
  }

  shipped.sort()
  writeFileSync(
    MANIFEST,
    `// Generated by scripts/convert-catalog-images.ts — do not edit by hand.
// The catalog images shipped under public/catalog/ (D-56). An AssetType's
// imageFile must be one of these.
export const CATALOG_IMAGE_FILES: readonly string[] = ${JSON.stringify(shipped, null, 2).replace(/"/g, "'")}
`,
  )

  console.log(`Converted ${shipped.length} images into ${OUTPUT_DIR}.`)
  if (missing.length > 0) console.log(`No photo yet (${missing.length}): ${missing.join(', ')}`)
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
