// D-53 (issue #183). Copies the IBM Plex woff2 files the app uses out of
// the @fontsource packages into public/fonts/ and writes
// app/assets/css/fonts.css, so the browser makes no third-party request
// and no font file is bundled that no page can ask for.
//
//   pnpm fonts:generate
//
// fontsource's per-subset CSS has no unicode-range, so two subsets of one
// family and weight cannot simply both be imported: the later face would
// shadow the earlier one. The faces are declared here instead, each with
// the exact range from the package's own unicode.json. latin carries
// a–z and á ä ô; latin-ext carries č š ž ľ ĺ ŕ ť ď ň.
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

interface Face {
  family: string
  packageName: string
  weights: number[]
}

// docs/design/interface-design-foundation.md §4.2: Sans 400/500/600 (body),
// Condensed 600 (display/label), Mono 400/600 (data).
const FACES: Face[] = [
  { family: 'IBM Plex Sans', packageName: 'ibm-plex-sans', weights: [400, 500, 600] },
  { family: 'IBM Plex Sans Condensed', packageName: 'ibm-plex-sans-condensed', weights: [600] },
  { family: 'IBM Plex Mono', packageName: 'ibm-plex-mono', weights: [400, 600] },
]
const SUBSETS = ['latin', 'latin-ext'] as const
const OUTPUT_DIR = 'public/fonts'
const CSS = 'app/assets/css/fonts.css'

function main() {
  rmSync(OUTPUT_DIR, { recursive: true, force: true })
  mkdirSync(OUTPUT_DIR, { recursive: true })

  let css = `/* Generated by scripts/generate-fonts.ts — do not edit by hand.
 * D-53: IBM Plex, self-hosted from /fonts, latin + latin-ext (Slovak
 * diacritics). Each face carries its subset's exact unicode-range, so a
 * page downloads only the files it needs. Licence: SIL OFL 1.1 (public/fonts/LICENSE.txt). */
`

  for (const face of FACES) {
    const root = join('node_modules/@fontsource', face.packageName)
    const unicode = JSON.parse(readFileSync(join(root, 'unicode.json'), 'utf8')) as Record<
      string,
      string
    >
    for (const weight of face.weights) {
      for (const subset of SUBSETS) {
        const file = `${face.packageName}-${subset}-${weight}-normal.woff2`
        copyFileSync(join(root, 'files', file), join(OUTPUT_DIR, file))
        const range = unicode[subset]
        if (!range) throw new Error(`${face.packageName}: no unicode-range for ${subset}`)
        css += `
@font-face {
  font-family: '${face.family}';
  font-style: normal;
  font-display: swap;
  font-weight: ${weight};
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${range};
}
`
      }
    }
  }

  copyFileSync('node_modules/@fontsource/ibm-plex-sans/LICENSE', join(OUTPUT_DIR, 'LICENSE.txt'))
  writeFileSync(CSS, css)
  console.log(
    `Wrote ${FACES.reduce((n, f) => n + f.weights.length * SUBSETS.length, 0)} faces to ${OUTPUT_DIR} and ${CSS}.`,
  )
}

main()
